"""Add content and category models

Revision ID: 4918c96ea78f
Revises: c44b7eb9fbad
Create Date: 2025-05-28 16:24:20.637097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4918c96ea78f'
down_revision = 'c44b7eb9fbad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###