"""Add assessment and quiz tables

Revision ID: 7b773d3e1643
Revises: d320f16aa387
Create Date: 2025-05-28 17:33:43.208125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b773d3e1643'
down_revision = 'd320f16aa387'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###