"""Add password_hash and refresh_token to users

Revision ID: 96e174832c9c
Revises: 4918c96ea78f
Create Date: 2025-05-28 16:34:09.976703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e174832c9c'
down_revision = '4918c96ea78f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###